The NewYork Times Page
Varun2323/NewYork-Times-Page pull request #1
Opened 2020-10-02 21:40 UTC by Varun2323

Description:
 The New York Times page, it shows a Subscribe Now and Log In button on the top-right corner of Navbar, a Main section related to news and a Footer section.

Header (Subscribe section):
- A link to another URL (if user wants to subscribe  or Log In).
- A button for Subscribe Now and Log In.

Main section:
- Embedded images , data and  different URLs for further information.
- A Grid applied with background image to make information more attractive.
- A concept of Flex container with Grid container inside.

Footer section:
- Defining about the different sections of news.
- Text related to legal information about the website.

2020-10-02 22:58 UTC, blackpintz requested changes
# Status: Changes Required.

## Hello team,

**Great job on your project. Your attention to details is quite remarkable.**

**Please make the following changes.**

### Mandatory

1). **Remove the page horizontal scroll.**

2). **The 'space & cosmos' text, on the navigation bar, is displaying on two lines instead of one line.**

original | clone
---------| -------
![newyork_original](https://user-images.githubusercontent.com/38922385/94973079-73306100-0513-11eb-9889-0abd31e96760.png) | ![newyork_clone](https://user-images.githubusercontent.com/38922385/94973092-7b889c00-0513-11eb-95bc-4da9b5bdc998.png)

3). **The navigation bar should stick at the top of the page.**

4). **Style the image caption for the image below. As it is, your image looks like it doesn't have a caption. And the caption looks like it is part of the long middle paragraph.**

original | clone
---------| -------
![bicep_original](https://user-images.githubusercontent.com/38922385/94973503-8ee83700-0514-11eb-8ceb-b2788928ea35.png) | ![bicep_clone](https://user-images.githubusercontent.com/38922385/94973530-a0314380-0514-11eb-9e51-ba4b43812a53.png)

5). **The image and side text, in the editor's pick section( see screenshot below), should be links.**

![editor_clone](https://user-images.githubusercontent.com/38922385/94973786-44b38580-0515-11eb-94f3-b49d36dfbf2b.png)

6). **A few things to change in the screenshotted section below.**

![space_clone](https://user-images.githubusercontent.com/38922385/94973875-8d6b3e80-0515-11eb-983e-5f4ada9bec2e.png)

- **The images and image captions should be links.**

- **Add the small text, directly below the images, and the dates below the image captions like in the original (see screenshot below).**
![space_original](https://user-images.githubusercontent.com/38922385/94974208-82fd7480-0516-11eb-845b-ccea848f66ff.png)

- **The content for the most popular section is overlapping each other.  Also, each line of content should be a link.** 

7). **Wrap all the content in the main section inside a `<main>` tag and all the content in the footer section inside a `footer` tag.**

8). **The new york times logo and all the list items on the top and bottom footer section should be links.**

9). **Please add the sticky menu below at the bottom of your page(screenshot from original page).**
![bottom_menu](https://user-images.githubusercontent.com/38922385/94974826-65c9a580-0518-11eb-8ebd-0aec1750249c.png)

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-10-02 22:58 UTC, blackpintz commented on index.html
> +        <!----------------Thanks for reading the Times section------------------->
Remove this comment because it doesn't highlight anything about your times section

2020-10-05 20:39 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing job so far. However, there are some changes that are required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] Two of your linter checks failed. Kindly fix all linter errors and ensure that the linter checks are all green.
![20:58:44](https://user-images.githubusercontent.com/26856491/95125932-947c9180-074d-11eb-9aa4-99fc2cbfcd62.png)

- [ ] The previous reviewer mentioned that you should link the images with their titles In your `Editor's Pick` section. This has not been fixed. You should let the anchor tag of each side text covers their individual images.

**Also in the bottom part of the page the previous reviewer mentioned that:**
- [ ] Each of the articles in the `More in Space and Astronomy` and the `Editors' Picks` sections should be linked. 
- This includes the image and title of each of the articles. You should make them clickable.

![21:10:00](https://user-images.githubusercontent.com/26856491/95126962-29cc5580-074f-11eb-9a5e-8d32ff9134bd.png)

- The same thing is applicable to the `Most Popular` section. Each of the titles should be linked.

![21:10:42](https://user-images.githubusercontent.com/26856491/95127080-52544f80-074f-11eb-9d8c-653805f8bb10.png)

- [ ] The fixed footer is missing in your project. Kindly add it and make it fixed to the bottom of your page.

![21:14:09](https://user-images.githubusercontent.com/26856491/95127356-c42c9900-074f-11eb-99ec-db564bedf1bd.png)

![21:37:40](https://user-images.githubusercontent.com/26856491/95129523-099e9580-0753-11eb-96a0-564ff79dcaa1.png)


- [ ] You are having some layout issues in the `The Theory of Inflation` section. Kindly compare them and fix them as appropriate.

Original page:
![21:33:05](https://user-images.githubusercontent.com/26856491/95129325-c6442700-0752-11eb-8a1f-f827f6be7b96.png)

Clone page:
![21:35:49](https://user-images.githubusercontent.com/26856491/95129334-c8a68100-0752-11eb-9161-4b0a448090da.png)

- Looking at the images above, it is clear that you need to work on your layout of the section mentioned.


**Other things to take care of in your footer section:**

- [ ] The New York Times logo in the footer section is linked. Kindly make it a link.

Original page:
![21:17:00](https://user-images.githubusercontent.com/26856491/95127675-44eb9500-0750-11eb-8e08-605341a245a4.png)

Clone page;
![21:17:31](https://user-images.githubusercontent.com/26856491/95127665-41580e00-0750-11eb-851e-48ba1662b4b4.png)

- [ ] Each of the footer items is also linked. Kindly make them links.

![21:22:11](https://user-images.githubusercontent.com/26856491/95128121-e1ae3280-0750-11eb-86c0-9db021e0fdd6.png)


**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-06 18:11 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello!! Great work on the project!

:100: sticky and footer navbar
:100: the website looks great

Required changes:
### [Mandatory] :red_circle: 

- [ ] the NYT logo should be a link

- [ ] eliminate ```cursors: pointer``` from css and convert link elements to anchor ```<a>``` HTML tags

- [ ] The preview screenshot has a leyend please remove it
![image](https://user-images.githubusercontent.com/25774518/95240249-bddf0100-07d1-11eb-8cdf-87ea93265bc9.png)

- [ ] ```footer-bottom``` elements should be links
![image](https://user-images.githubusercontent.com/25774518/95240437-039bc980-07d2-11eb-901f-d5cb69c20afe.png)

- [ ] social elements should be links
![image](https://user-images.githubusercontent.com/25774518/95241553-88d3ae00-07d3-11eb-9769-f71c18eb2a3e.png)
![image](https://user-images.githubusercontent.com/25774518/95241620-9f7a0500-07d3-11eb-9167-807b261e4514.png)

- [ ] wrapped what does not form part of the navbar and the footer in a ```<main>``` container, as suggested in previous review.

- [ ] missing element as mention in previous review
![image](https://user-images.githubusercontent.com/25774518/95242201-77d76c80-07d4-11eb-8eda-416f3b46d9c0.png)

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-06 21:09 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

#### Hello @Varun2323, Great job! 👏  
You have done well on this project. Well done 👍 
Let's make a few changes, and we will be done.

- [ ] Fix the HTML validation warnings/errors, use the [w3 Validator](https://validator.w3.org/)

- [ ] Fix the linter errors

- [ ] In this project we have to make sure nothing is messed up, aligned the text properly to the left of the image. 
<img width="318" alt="Screen Shot 2020-10-06 at 10 01 24 PM" src="https://user-images.githubusercontent.com/5264771/95260032-f73e5d80-081f-11eb-9b48-ab41ad2e0693.png">

- [ ] Your '**theory of inflation**' section is not correctly implemented. Each of the grids is supposed to have their own background image, not a single image for the entire area, [see how sprite images work](https://www.w3schools.com/css/css_image_sprites.asp) for more details.
<img width="890" alt="Screen Shot 2020-10-06 at 9 59 14 PM" src="https://user-images.githubusercontent.com/5264771/95260342-759aff80-0820-11eb-8d49-779fb89a2fa6.png">


Make these changes and submit another code review request 🙏 

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-10-06 22:06 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Great job working on the required changes!!

There are still some issues related to previously required changes.

### [Mandatory] :red_circle: 

- [ ] Use semantic HTML for ```header```, ```main```, ```article```, and ```footer```. Example:
**Actual**: ``` <section class='header> ... </section>```
**Improved** :+1: : ``` <header class='header> ... </header>```

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-06 22:22 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

You may now merge to master.

Please before submitting fix the alignment and indentation of the HTML file.

## Great work! :clap: :clap:, See you at the top :rocket: !!!

2020-10-06 22:29 UTC, merged